backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: "Zawodnicy"
    name: "zawodnicy"
    files:
      - label: "Zawodnicy"
        name: "zawodnicy"
        file: "content/druzyna.json"
        fields:
          - label: team
            name: team
            widget: list
            fields:
              - {label: name, name: name, widget: string}
              - {label: numer Zawodnika, name: numer, widget: number}
              - {label: pozycja, name: pozycja, widget: select, options: ["bramkarz", "obrońca", "pomocnik","napastnik"]}
              - {label: bramki, name: bramki, widget: number}
              - {label: asysty, name: asysty, widget: number}
              - {label: żółte kartki, name: zKartki, widget: number}
              - {label: czerwone kartki, name: cKartki, widget: number}
              - {label: mecze, name: mecze, widget: number}
              - {label: Photo, name: photo, widget: image, required: false}
  - label: "mecze"
    name: "mecze"
    files:
      - label: "mecz"
        name: "mecz"
        file: "content/mecz.json"
        fields:
          - label: mecz
            name: mecz
            widget: list
            fields:
              - {label: gospodarze, name: gospodarze, widget: string}
              - {label: logo gospodarzy, name: gospodarzeLogo, widget: image}
              - {label: goscie, name: goscie, widget: string}
              - {label: logo gosci, name: goscieLogo, widget: image}
              - {label: bramki gospodarza, name: bramkiGospodarza , widget: number}
              - {label: bramki goscia, name: bramkiGoscia , widget: number}
              - {label: Data, name: data , widget: date, format: 'D.MM.YYYY'}
  - name: 'Aktualnosci'
    label: 'Aktualnosci'
    folder: 'content/blog'
    create: true
    path: '{{id}}'
    editor:
      preview: true
    fields:
      - { label: 'id', name: 'id', widget: 'number', required: true}
      - { label: 'naglowek', name: 'naglowek', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'date', format: "DD-MM-YYYY"}
      - { label: "Featured Image", name: "thumbnail", widget: "image", choose_url: true, media_library: config: multiple: true, media_folder: "/static/images/slider3.jpg"  }
      - { label: 'tresc', name: 'tresc', widget: 'markdown' }

  - label: "Tabela"
    name: "tabela"
    files:
      - label: "tabela senior"
        name: "tabela"
        file: "content/tabelaSenior.json"
        fields:
          - label: Tabela Senior
            name: Tabela
            widget: list
            fields:
              - {label: druzyna, name: druzyna, widget: string}
              - {label: logo, name: logo, widget: image, required: false}
              - {label: Mecze, name: mecze, widget: number}
              - {label: zwyciestwa, name: zwyciestwa, widget: number}
              - {label: porazki, name: porazki , widget: number}
              - {label: remisy, name: remisy , widget: number}
              - {label: bramki, name: bramki , widget: number}
              
          - label: Tabela Junior
            name: TabelaJunior
            widget: list
            fields:
              - {label: druzyna, name: druzyna, widget: string}
              - {label: logo, name: logo, widget: image, required: false}
              - {label: Mecze, name: mecze, widget: number}
              - {label: zwyciestwa, name: zwyciestwa, widget: number}
              - {label: porazki, name: porazki , widget: number}
              - {label: remisy, name: remisy , widget: number}
              - {label: bramki, name: bramki , widget: number}
      
          
 
    
    
# default: "/content/blog/images/slider3.jpg", media_folder: "/static/images/slider3.jpg"