backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: "Zawodnicy"
    name: "zawodnicy"
    files:
      - label: "Zawodnicy"
        name: "zawodnicy"
        file: "content/druzyna.json"
        fields:
          - label: Team
            name: team
            widget: list
            fields:
              - {label: name, name: name, widget: string}
              - {label: numer Zawodnika, name: numer, widget: number}
              - {label: pozycja, name: pozycja, widget: string, options: ["napastnik", "bramkarz", "obrońca"]}
              - {label: bramki, name: bramki, widget: number}
              - {label: asysty, name: asysty, widget: number}
              - {label: żółte kartki, name: zKartki, widget: number}
              - {label: czerwone kartki, name: cKartki, widget: number}
              - {label: mecze, name: mecze, widget: number}
              - {label: Photo, name: photo, widget: image, required: false}
  
  
      
  
  
