backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: "Zawodnicy"
    name: "zawodnicy"
    files:
      - label: "Zawodnicy"
        name: "team"
        file: "content/druzyna.json"
        fields:
          - name: team
            widget: list
            fields:
              - {label: name, name: name, widget: string}
              - {label: numer Zawodnika, name: numer, widget: number}
              - {label: pozycja, name: pozycja, widget: select, options: ["bramkarz", "obrońca", "pomocnik","napastnik"]}
              - {label: bramki, name: bramki, widget: number}
              - {label: asysty, name: asysty, widget: number}
              - {label: żółte kartki, name: zKartki, widget: number}
              - {label: czerwone kartki, name: cKartki, widget: number}
              - {label: mecze, name: mecze, widget: number}
              - {label: Photo, name: photo, widget: image, required: false}
  - label: "mecze"
    name: "mecze"
    files:
      - label: "mecz"
        name: "mecz"
        file: "content/mecz.json"
        fields:
          - {label: Wybierz aktualny sezon, name: AktualnySezon, widget: relation, collection: mecze, search_fields: [sezon.*.sezon], display_fields: [sezon.*.sezon], value_field: sezon.*.sezon}
          - name: sezon
            widget: list
            fields:
              - {label: sezon, name: sezon, widget: string}
              - name: mecz
                widget: list
                fields:
                  - {label: Data, name: data , widget: date, date_format: 'DD-MM-YYYY', time_format: "HH:mm",format: "L",picker_utc: false}
                  - {label: gospodarze, name: gospodarze, widget: string}
                  - {label: przeciwnik, name: przeciwnik, widget: string}
                  - {label: godzina, name: godzina , widget: string}
                  - {label: miejsce, name: miejsce, widget: string}
                  - label: Zawodnicy
                    name: Zawodnicy
                    widget: list
                    fields:
                    - {label: "Zawodnicy",
                          name: "Zawodnicy",
                          widget: "relation",
                          collection: zawodnicy,
                          search_fields: [team.*.name],
                          display_fields: [team.*.name],
                          value_field: team.*.name}
                    - {label: Rozegrane minuty, name: minuty, widget: number}
                    - {label: Żółte Kartki, name: ZKartki, widget: number,default: 0}
                    - {label: Czerwone Kartki, name: CKartki, widget: number,default: 0}
                  - label: Statystyki
                    name: Statystyki
                    widget: list
                    max: 1
                    min: 0
                    fields:
                      - label: Bramki PFT
                        name: BramkiPFT
                        widget: list
                        fields:
                          - {label: "Zawodnicy",
                                name: "Zawodnicy",
                                widget: "relation",
                                collection: zawodnicy,
                                search_fields: [team.*.name],
                                display_fields: [team.*.name],
                                value_field: team.*.name}
                          - {label: minuta, name: minuta, widget: number}
                      - label: Bramki Przeciwnika
                        name: BramkiPrzeciwnika
                        widget: list
                        fields:
                          - {label: Imię i nazwisko, name: name, widget: string}
                          - {label: minuta, name: minuta, widget: number}
                      - label: Kartki
                        name: Kartki
                        widget: list
                        fields:
                          - {label: "Zawodnicy",
                                name: "Zawodnicy",
                                widget: "relation",
                                collection: zawodnicy,
                                search_fields: [team.*.name],
                                display_fields: [team.*.name],
                                value_field: team.*.name}
                          - {label: kartka, name: kartka, widget: "select", options: ["żółta", "czerwona"]}                      
                          - {label: minuta, name: minuta, widget: number}
                      - label: Zmiany
                        name: Zmiany
                        widget: list
                        fields:
                          - {label: "Zmiana z",
                                name: "ZmianaZ",
                                widget: "relation",
                                collection: zawodnicy,
                                search_fields: [team.*.name],
                                display_fields: [team.*.name],
                                value_field: team.*.name}                      
                          - {label: minuta, name: minuta, widget: number}
                          - {label: "Zmiana na",
                                name: "ZmianaNa",
                                widget: "relation",
                                collection: zawodnicy,
                                search_fields: [team.*.name],
                                display_fields: [team.*.name],
                                value_field: team.*.name}
              
          
                                          
                      
                
              
  - name: 'Aktualnosci'
    label: 'Aktualnosci'
    folder: 'content/blog'
    create: true
    path: '{{id}}'
    editor:
      preview: true
    fields:
      - { label: 'id', name: 'id', widget: 'number', required: true}
      - { label: 'naglowek', name: 'naglowek', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'date', format: "DD-MM-YYYY"}
      - { label: "zdjecia", name: "zdjecia", widget: "image", choose_url: true, default: "/img/test.jpg", media_folder: /static/img/}
      - { label: 'tresc', name: 'tresc', widget: 'markdown', required: false }

  - label: "Tabela"
    name: "tabela"
    files:
      - label: "tabela senior"
        name: "tabela"
        file: "content/tabelaSenior.json"
        fields:
          - label: Tabela Senior
            name: Tabela
            widget: list
            fields:
              - {label: druzyna, name: druzyna, widget: string}
              - {label: logo, name: logo, widget: image, required: false}
              - {label: Mecze, name: mecze, widget: number}
              - {label: bramki, name: bramki , widget: number}
              
          - label: Tabela Junior
            name: TabelaJunior
            widget: list
            fields:
              - {label: druzyna, name: druzyna, widget: string}
              - {label: logo, name: logo, widget: image, required: false}
              - {label: Mecze, name: mecze, widget: number}
              - {label: zwyciestwa, name: zwyciestwa, widget: number}
              - {label: porazki, name: porazki , widget: number}
              - {label: remisy, name: remisy , widget: number}
              - {label: bramki, name: bramki , widget: number}
  - label: "O klubie"
    name: "Oklubie"
    files:
      - label: "Oklubie"
        name: "Oklubie"
        file: "content/oKlubieData.json"
        fields:
          - label: zarzad
            name: zarzad
            widget: list
            fields:
              - {label: Imie i nazwisko, name: name, widget: string}
              - {label: funkcja, name: funkcja, widget: string}
          - {label: Dodatkowy tekst, name: tekst, widget: 'markdown'}
          - label: Osiagniecia
            name: Osiagniecia
            widget: list
            fields:
                - {label: rok, name: year, widget: number}
                - label: osiagniecie
                  name: osiagniecie
                  widget: list
                  fields:
                    - {label: osiagniecie, name: osiagniecie, widget: string}
  - name: 'Produkty'
    label: 'Produkty'
    folder: 'content/blog/Produkty'
    create: true
    path: '{{name}}'
    editor:
      preview: true
    fields:
      - { label: 'nazwa', name: 'name', widget: 'string', required: true}
      - { label: 'cena', name: 'price', widget: 'string' }
      - {label: "Featured Image", name: "thumbnail", widget: "image", choose_url: true, default: "/img/prod/test.png"}


              
          
 
    
    
# default: "/content/blog/images/slider3.jpg", media_folder: "/static/images/slider3.jpg"